name: Run Tests
on:
  pull_request:
    branches:
     - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Run Tests
        run: npm ci
      - name: Validate
        run: npm run validate
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
